spring:
  application:
    name: names-manager
  datasource:
    url: jdbc:mysql://localhost:3306/names-app
    username: zel
    password: cheese
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8085
    
